/**
 * Word Ladder — level-by-level BFS, generating neighbors letter by letter.
 * Time O(N · L · 26) set lookups (N words, length L; each lookup hashes L chars),
 * Space O(N · L)
 *
 * Words are nodes; one-letter changes are edges. BFS from beginWord finds the
 * shortest ladder. Neighbors are generated by trying all 26 letters at every
 * position and keeping those still in the unvisited set; deleting a word from
 * the set when it's enqueued marks it visited.
 */
function ladderLength(beginWord, endWord, wordList) {
  const unvisited = new Set(wordList);
  if (!unvisited.has(endWord)) return 0;
  unvisited.delete(beginWord);

  const a = 'a'.charCodeAt(0);
  let level = [beginWord];
  let length = 1;

  while (level.length) {
    length++;
    const next = [];
    for (const word of level) {
      for (let i = 0; i < word.length; i++) {
        const before = word.slice(0, i);
        const after = word.slice(i + 1);
        for (let k = 0; k < 26; k++) {
          const candidate = before + String.fromCharCode(a + k) + after;
          if (!unvisited.has(candidate)) continue;
          if (candidate === endWord) return length;
          unvisited.delete(candidate);
          next.push(candidate);
        }
      }
    }
    level = next;
  }
  return 0;
}

module.exports = ladderLength;
